lite-youtube.js

fix(safari): fixed style within shadow fails on Safari

---

README.md
demo/index.html
lite-youtube.js

feat(time): add video start time attr

---

lite-youtube.js

fix(iframe): loader missing flag check

---

lite-youtube.js

fix(css): change activation header precedent for hiding

---

.eslintrc.js
.gitignore
lite-youtube.ts
package.json
tsconfig.json
yarn.lock

- Convert to TypeScript
- Add TS support for eslint
- Add lint npm-script

Convert to TypeScript

---

lite-youtube.ts
yarn.lock

fix: intersection observer injection no longer autoplays

---

README.md
demo/index.html
lite-youtube.ts

feat: add poster quality attr

---

README.md
demo/index.html
lite-youtube.ts

feat: add youtube-nocookie bool attr

---

README.md
demo/index.html
lite-youtube.ts

feat: add playlist loading support

---

README.md
demo/index.html
demo/shorts.html
lite-youtube.ts
test/lite-youtube.test.ts

feat(core): add YouTube Shorts-style mobile embed interaction

---

package.json

fix: Make the package a valid ES module

---

lite-youtube.ts
test/lite-youtube.test.ts

fix: resolve dead case path, add observe and coverage

---

demo/aspect-ratio.html
lite-youtube.ts
package.json
test/lite-youtube.test.ts
yarn.lock

feat(aspect-ratio): add css custom prop for changing aspect ratio of container

---

demo/frame-shadow.html
lite-youtube.ts
test/lite-youtube.test.ts

feat(frame-shadow): add ability to toggle frame::before shadow

---

demo/auto-pause.html
lite-youtube.ts
test/lite-youtube.test.ts

feat(auto-pause): adds autopause attribute for pausing videos off screen

---

lite-youtube.ts
test/lite-youtube.test.ts

feat(iframe): adds credentialless attribute for COEP

---

lite-youtube.ts
package.json
test/lite-youtube.test.ts
yarn.lock

Resolves #87 
Differs from https://github.com/paulirish/lite-youtube-embed/issues/105 because we inject into the lightdom above other nodes within lite-youtube so that our slots work for poster overrides. But still same concept. :100:

feat(search): add noscript injector to lightdom for search indexing

---

demo/no-image.html
lite-youtube.ts
test/lite-youtube.test.ts

Changed my mind on this after much poking.
Resolves #79 #97 #78 #102

feat(yt-404): handle when posters do not exist

---

lite-youtube.ts
test/lite-youtube.test.ts

feat(noscript): allow disabling of noscript lightdom inject

---

README.md

doc(autopause): clarify custom poster behavior

---

README.md
demo/play-button-style.html
lite-youtube.ts

feat: add support for stying the playButton
